name: Playwright Tests

on:
  workflow_dispatch:  # Only manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      id: playwright
      run: npx playwright test --reporter=json,html
      continue-on-error: true
      
    - name: Create summary report
      if: always()
      run: |
        echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "playwright-report/results.json" ]; then
          # Parse the JSON results to extract test counts
          PASSED=$(grep -o '"status":"passed"' playwright-report/results.json | wc -l)
          FAILED=$(grep -o '"status":"failed"' playwright-report/results.json | wc -l)
          FLAKY=$(grep -o '"status":"flaky"' playwright-report/results.json | wc -l)
          SKIPPED=$(grep -o '"status":"skipped"' playwright-report/results.json | wc -l)
          
          echo "✅ **Passed:** $PASSED" >> $GITHUB_STEP_SUMMARY
          echo "❌ **Failed:** $FAILED" >> $GITHUB_STEP_SUMMARY
          echo "⚠️ **Flaky:** $FLAKY" >> $GITHUB_STEP_SUMMARY
          echo "⏭️ **Skipped:** $SKIPPED" >> $GITHUB_STEP_SUMMARY
          
          # Set job status based on test results
          if [ $FAILED -gt 0 ]; then
            echo "::error::$FAILED tests failed"
          fi
        else
          echo "⚠️ No test results found" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30